version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    container_name: vue-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app # ONLY development
      - /app/node_modules
    command: >
      sh -c "if [ \"$NODE_ENV\" = \"development\" ]; then npm run dev; else npm run start; fi"
