version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/mysql-init:/docker-entrypoint-initdb.d

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
      composer install &&
      if [ ! -f .env ]; then
        cp .env.example .env;
      fi &&
      if ! grep -q '^APP_KEY=' .env || [ -z \"$(grep '^APP_KEY=' .env | cut -d '=' -f2)\" ]; then
        echo 'Gerando APP_KEY...';
        php artisan key:generate --ansi || echo 'Erro ao gerar APP_KEY!';
      fi &&
      if ! grep -q '^JWT_SECRET=' .env || [ -z \"$(grep '^JWT_SECRET=' .env | cut -d '=' -f2)\" ]; then
        echo 'Gerando JWT_SECRET...';
        php artisan jwt:secret --force || echo 'Erro ao gerar JWT_SECRET!';
      fi &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=80
      "

volumes:
  mysql-data:
